#!/bin/sh

# shellcheck disable=SC2034,SC3043,SC1091

## Copyright (C) 2019 - 2025 ENCRYPTED SUPPORT LLC <adrelanos@whonix.org>
## See the file COPYING for copying conditions.

#set -x

true "dist-base-files $0: START"

## style-ok: no-strict - must maintain the same style as other grub.d scripts.
set -e
set -o allexport

make_boot_entry='true'

: "${persistence_type:="PERSISTENT"}"
: "${session_detail:="daily activities"}"

grub_distributor_appendix="${persistence_type} Mode | USER Session | ${session_detail}"
GRUB_DISTRIBUTOR="${grub_distributor_appendix}"

GRUB_DISABLE_RECOVERY="true"

if test -x /etc/grub.d/10_00_linux_dist ; then
	/etc/grub.d/10_00_linux_dist
fi

true "dist-base-files $0: OK: END"
